import type { Metadata } from "next";
import { BRAND, absoluteUrl, clampMeta, displayCityName } from "@/lib/seo/site";
import type { CityListing } from "@/lib/seo/profiles";
import type { EscortProfile } from "@/lib/profiles-data";

/**
 * The site-wide social card generated by app/opengraph-image.tsx.
 *
 * Declaring a page-level `openGraph` object replaces the root layout's object
 * wholesale, which silently drops the file-generated image, so every page that
 * overrides Open Graph has to re-point at it.
 */
const OG_IMAGE = "/opengraph-image";

/** Metadata for the main commercial service page (/escorts). */
export function buildServicePageMetadata(profileCount: number): Metadata {
  const countText =
    profileCount === 1 ? "1 public profile" : `${profileCount} public profiles`;

  return {
    title: "Escorts & Call Girls in India | Verified Profiles",
    description: clampMeta(
      `Browse ${countText} of independent escorts, call girls and companions in India. ` +
        `City-wise listings with real photos, published rates and direct contact.`,
      160
    ),
    alternates: { canonical: absoluteUrl("/escorts") },
    openGraph: {
      title: "Escorts & Call Girls in India | Verified Profiles",
      description: clampMeta(
        `City-wise listings of independent escorts, call girls and companions in India, with real photos and published rates.`,
        200
      ),
      url: absoluteUrl("/escorts"),
      type: "website",
      images: [OG_IMAGE],
    },
  };
}

/**
 * Metadata for a city landing page. `count` is the real number of publicly
 * listable profiles, so the description never overstates the page.
 */
export function buildCityMetadata(city: CityListing): Metadata {
  const plural = city.count === 1;
  const title = `Escorts in ${city.name} | Call Girls & Companions`;
  const description = clampMeta(
    plural
      ? `Browse 1 verified escort and call girl in ${city.name}. Real photos, published rates and direct contact on ${BRAND}.`
      : `Browse ${city.count} verified escorts and call girls in ${city.name}. Real photos, published rates and direct contact on ${BRAND}.`,
    160
  );

  return {
    title,
    description,
    alternates: { canonical: absoluteUrl(`/city/${city.slug}`) },
    openGraph: {
      title: `${title} | ${BRAND}`,
      description,
      url: absoluteUrl(`/city/${city.slug}`),
      type: "website",
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} | ${BRAND}`,
      description,
    },
  };
}

/**
 * The first sentence of a bio, but only when it actually describes this person
 * in this city.
 *
 * Real bios are the best possible meta description, but the directory also
 * contains bios that are keyword filler advertising a different city. Quoting
 * those into a title/description would be both inaccurate and exactly the
 * spam pattern this work is meant to avoid, so anything that does not mention
 * the profile's own city is rejected in favour of a factual description.
 */
function usableBioSentence(profile: EscortProfile): string | null {
  const bio = (profile.about ?? "").replace(/\s+/g, " ").trim();
  if (!bio) return null;

  const first = bio.split(/(?<=[.!?])\s/)[0]?.trim() ?? "";
  if (first.length < 40 || first.length > 200) return null;

  const cityWords = displayCityName(profile.city)
    .toLowerCase()
    .split(/\s+/)
    .filter((word) => word.length > 2);
  if (!cityWords.some((word) => first.toLowerCase().includes(word))) return null;

  return first;
}

/** Metadata for a public profile page. The title template adds the brand. */
export function buildProfileMetadata(profile: EscortProfile): Metadata {
  // Stored city values are free text ("delhi"), so normalise for a clean title.
  const city = displayCityName(profile.city);
  const url = absoluteUrl(`/profile/${profile.id}`);

  const description = clampMeta(
    usableBioSentence(profile) ??
      (() => {
        if (profile.status === "Agency") return `${profile.name} is an agency companion listed in ${city}.`;
        if (profile.status === "Independent") return `${profile.name} is an independent companion listed in ${city}.`;
        return `${profile.name} is a companion listed in ${city}.`;
      })() + ` View photos, services and published rates, and contact ${BRAND} directly.`,
    160
  );

  return {
    title: `${profile.name} — Escort in ${city}`,
    description,
    alternates: { canonical: url },
    openGraph: {
      title: `${profile.name} — Escort in ${city}`,
      description,
      url,
      type: "profile",
      images: profile.photoUrl
        ? [{ url: absoluteUrl(profile.photoUrl), alt: `${profile.name} in ${city}` }]
        : [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: `${profile.name} — Escort in ${city}`,
      description,
    },
  };
}
