import type { Metadata } from "next";
import { BRAND, absoluteUrl, clampMeta, displayCityName } from "@/lib/seo/site";
import type { CityListing } from "@/lib/seo/profiles";
import type { EscortProfile } from "@/lib/profiles-data";
import { INDIA_LOCATIONS } from "@/lib/india-locations";

/**
 * The site-wide social card generated by app/opengraph-image.tsx.
 *
 * Declaring a page-level `openGraph` object replaces the root layout's object
 * wholesale, which silently drops the file-generated image, so every page that
 * overrides Open Graph has to re-point at it.
 */
const OG_IMAGE = "/opengraph-image";

/** Metadata for the main commercial service page (/escorts). */
export function buildServicePageMetadata(profileCount: number): Metadata {
  const countText =
    profileCount === 1 ? "1 public profile" : `${profileCount} public profiles`;

  return {
    title: "Escorts & Call Girls in India | Verified Profiles",
    description: clampMeta(
      `Browse ${countText} of independent escorts, call girls and companions in India. ` +
        `City-wise listings with real photos, published rates and direct contact.`,
      160
    ),
    alternates: { canonical: absoluteUrl("/escorts") },
    openGraph: {
      title: "Escorts & Call Girls in India | Verified Profiles",
      description: clampMeta(
        `City-wise listings of independent escorts, call girls and companions in India, with real photos and published rates.`,
        200
      ),
      url: absoluteUrl("/escorts"),
      type: "website",
      images: [OG_IMAGE],
    },
  };
}

/**
 * Metadata for a city landing page. `count` is the real number of publicly
 * listable profiles, so the description never overstates the page.
 */
export function buildCityMetadata(city: CityListing): Metadata {
  const plural = city.count === 1;
  const title = `Escorts in ${city.name} | Call Girls & Companions`;
  const description = clampMeta(
    `Browse verified independent escorts and call girls in ${city.name}. Real photos, published rates and direct contact on ${BRAND}. Find companions across ${city.name}.`,
    160
  );

  return {
    title,
    description,
    alternates: { canonical: absoluteUrl(`/city/${city.slug}`) },
    openGraph: {
      title: `${title} | ${BRAND}`,
      description,
      url: absoluteUrl(`/city/${city.slug}`),
      type: "website",
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} | ${BRAND}`,
      description,
    },
  };
}

/**
 * Cities a bio may be *about*, as opposed to the city the profile is filed
 * under. Derived from the same reference data the directory's own location
 * filters use, so this list cannot drift from the geography the site accepts.
 *
 * Built once at module load: `bioAdvertisesOtherCity` runs on every profile
 * render, and rebuilding the set each time would walk all ~30 states for
 * nothing.
 */
const KNOWN_CITY_NAMES = new Set(
  INDIA_LOCATIONS.flatMap((state) =>
    state.districts.flatMap((district) => district.cities.map((city) => city.name))
  )
);

/**
 * True when a bio is written about a city other than the one it is filed under.
 *
 * Real bios are the best possible body copy for a profile, but the directory
 * also receives bios that are keyword filler for a different city — the live
 * data has two Delhi listings whose bios are entirely about Chandigarh. Those
 * are not a moderation decision, they are a defect: the page ends up ranking for
 * a city its owner is not in, which is the doorway-page pattern this whole SEO
 * layer exists to avoid. When detected, the bio is suppressed in favour of a
 * factual description rather than published.
 *
 * Detection is deliberately narrow — it only fires on a *different* known city
 * appearing repeatedly. A passing mention of another city in an otherwise
 * on-topic bio is normal and is left alone.
 */
export function bioAdvertisesOtherCity(profile: EscortProfile): boolean {
  const bio = (profile.about ?? "").replace(/\s+/g, " ").trim();
  if (bio.length < 80) return false;

  // Compared in lower case: stored bios capitalise city names on first use
  // ("Chandigarh escorts"), and a case-sensitive count would miss every one.
  const haystack = bio.toLowerCase();
  const own = displayCityName(profile.city).toLowerCase();

  for (const name of KNOWN_CITY_NAMES) {
    const city = name.toLowerCase();
    if (city === own || city.length <= 3) continue;
    // Requires 3+ mentions so an incidental reference is never mistaken for
    // the subject of the bio.
    if (haystack.split(city).length - 1 >= 3) return true;
  }

  return false;
}

/**
 * The first sentence of a bio, but only when it actually describes this person
 * in this city.
 *
 * Real bios are the best possible meta description, but the directory also
 * contains bios that are keyword filler advertising a different city. Quoting
 * those into a title/description would be both inaccurate and exactly the
 * spam pattern this work is meant to avoid, so anything that does not mention
 * the profile's own city is rejected in favour of a factual description.
 */
function usableBioSentence(profile: EscortProfile): string | null {
  const bio = (profile.about ?? "").replace(/\s+/g, " ").trim();
  if (!bio) return null;

  // A bio that is really about another city is never quoted, however well it
  // reads or however well it scores.
  if (bioAdvertisesOtherCity(profile)) return null;

  const first = bio.split(/(?<=[.!?])\s/)[0]?.trim() ?? "";
  if (first.length < 40 || first.length > 200) return null;

  const cityWords = displayCityName(profile.city)
    .toLowerCase()
    .split(/\s+/)
    .filter((word) => word.length > 2);
  if (!cityWords.some((word) => first.toLowerCase().includes(word))) return null;

  return first;
}

/** Metadata for a public profile page. The title template adds the brand. */
export function buildProfileMetadata(profile: EscortProfile): Metadata {
  // Stored city values are free text ("delhi"), so normalise for a clean title.
  const city = displayCityName(profile.city);
  const url = absoluteUrl(`/profile/${profile.id}`);

  const description = clampMeta(
    usableBioSentence(profile) ??
      (() => {
        if (profile.status === "Agency") return `${profile.name} is an agency companion listed in ${city}.`;
        if (profile.status === "Independent") return `${profile.name} is an independent companion listed in ${city}.`;
        return `${profile.name} is a companion listed in ${city}.`;
      })() + ` View photos, services and published rates, and contact ${BRAND} directly.`,
    160
  );

  return {
    title: `${profile.name} — Escort in ${city}`,
    description,
    alternates: { canonical: url },
    openGraph: {
      title: `${profile.name} — Escort in ${city}`,
      description,
      url,
      type: "profile",
      images: profile.photoUrl
        ? [{ url: absoluteUrl(profile.photoUrl), alt: `${profile.name} in ${city}` }]
        : [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: `${profile.name} — Escort in ${city}`,
      description,
    },
  };
}
